-- =====================================================================
-- NCL-01-CN-001 Đăng nhập hệ thống: tài khoản, vai trò, phiên, nhật ký đăng nhập
-- =====================================================================

-- Vai trò nhân viên (VT-01 … VT-13). VT-14 "Nhân viên phòng tập" là vai trò chung,
-- mọi tài khoản nhân viên đều có nên không cần dòng riêng.
CREATE TABLE roles (
    id                      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(50)  NOT NULL,
    name                    VARCHAR(100) NOT NULL,
    requires_counter_device BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order              INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uq_roles_code UNIQUE (code)
);

COMMENT ON COLUMN roles.requires_counter_device IS
    'Vai trò chỉ được đăng nhập trên máy quầy đã đăng ký với câu lạc bộ (lễ tân)';

INSERT INTO roles (code, name, requires_counter_device, sort_order) VALUES
    ('CHAIN_OWNER',      'Chủ phòng tập',               FALSE, 10),
    ('CLUB_MANAGER',     'Quản lý câu lạc bộ',          FALSE, 20),
    ('SALES_CONSULTANT', 'Nhân viên tư vấn',            FALSE, 30),
    ('RECEPTIONIST',     'Lễ tân',                      TRUE,  40),
    ('PERSONAL_TRAINER', 'Huấn luyện viên cá nhân',     FALSE, 50),
    ('GROUP_TRAINER',    'Huấn luyện viên lớp nhóm',    FALSE, 60),
    ('ACCOUNTANT',       'Kế toán',                     FALSE, 70),
    ('TECHNICIAN',       'Nhân viên kỹ thuật',          FALSE, 80),
    ('MEMBER_CARE',      'Nhân viên chăm sóc hội viên', FALSE, 90),
    ('ADMIN',            'Quản trị viên',               FALSE, 100);

CREATE TABLE users (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              VARCHAR(50)  NOT NULL,
    password_hash         VARCHAR(100) NOT NULL,
    full_name             VARCHAR(150) NOT NULL,
    job_title             VARCHAR(100),
    phone_number          VARCHAR(20),
    status                VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,
    all_branches          BOOLEAN      NOT NULL DEFAULT FALSE,
    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    last_login_at         TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_username_format CHECK (username ~ '^[a-z0-9._-]{3,50}$'),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_users_failed_login_attempts CHECK (failed_login_attempts >= 0)
);

COMMENT ON COLUMN users.username IS 'Tên đăng nhập, luôn lưu chữ thường để so khớp không phân biệt hoa thường';
COMMENT ON COLUMN users.password_hash IS 'Bản băm BCrypt, không bao giờ lưu mật khẩu rõ';
COMMENT ON COLUMN users.all_branches IS 'Phạm vi toàn chuỗi; FALSE thì dùng user_branch_scopes';
COMMENT ON COLUMN users.failed_login_attempts IS 'Số lần nhập sai mật khẩu liên tiếp';
COMMENT ON COLUMN users.locked_until IS 'Thời điểm hết tạm khóa đăng nhập do nhập sai nhiều lần';

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

-- Phiên làm việc lưu ở máy chủ để hết phiên khi không thao tác và chấm dứt phiên ngay khi cần.
-- Khóa ngoại tới counter_devices / branches được thêm ở V2.
CREATE TABLE user_sessions (
    id               UUID         PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES users (id),
    client_type      VARCHAR(20)  NOT NULL,
    device_id        BIGINT,
    branch_id        BIGINT,
    ip_address       VARCHAR(45),
    user_agent       VARCHAR(512),
    created_at       TIMESTAMPTZ  NOT NULL,
    last_activity_at TIMESTAMPTZ  NOT NULL,
    expires_at       TIMESTAMPTZ  NOT NULL,
    ended_at         TIMESTAMPTZ,
    end_reason       VARCHAR(30),
    CONSTRAINT ck_user_sessions_client_type CHECK (client_type IN ('COUNTER', 'OFFICE', 'MOBILE')),
    CONSTRAINT ck_user_sessions_counter_device CHECK ((client_type = 'COUNTER') = (device_id IS NOT NULL)),
    CONSTRAINT ck_user_sessions_end_reason CHECK (end_reason IN ('LOGOUT', 'IDLE_TIMEOUT', 'ABSOLUTE_TIMEOUT', 'REVOKED')),
    CONSTRAINT ck_user_sessions_ended CHECK ((ended_at IS NULL) = (end_reason IS NULL))
);

CREATE INDEX ix_user_sessions_user_open ON user_sessions (user_id) WHERE ended_at IS NULL;

-- Nhật ký đăng nhập: chỉ thêm mới (QTN-02).
CREATE TABLE auth_audit_logs (
    id          BIGINT        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_type  VARCHAR(40)   NOT NULL,
    reason_code VARCHAR(40),
    user_id     BIGINT        REFERENCES users (id),
    username    VARCHAR(100),
    session_id  UUID,
    client_type VARCHAR(20),
    device_id   BIGINT,
    branch_id   BIGINT,
    ip_address  VARCHAR(45),
    user_agent  VARCHAR(512),
    detail      VARCHAR(1000) NOT NULL,
    occurred_at TIMESTAMPTZ   NOT NULL,
    CONSTRAINT ck_auth_audit_logs_event_type CHECK (event_type IN (
        'LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'ACCOUNT_TEMPORARILY_LOCKED', 'LOGIN_REJECTED',
        'LOGOUT', 'SESSION_EXPIRED', 'DEVICE_REGISTERED'))
);

COMMENT ON TABLE auth_audit_logs IS 'Nhật ký đăng nhập và phiên, chỉ thêm mới, không sửa xóa (QTN-02)';
COMMENT ON COLUMN auth_audit_logs.username IS 'Tên đăng nhập người dùng đã nhập, kể cả khi không tồn tại';
COMMENT ON COLUMN auth_audit_logs.detail IS 'Nội dung sự kiện bằng tiếng Việt';

CREATE INDEX ix_auth_audit_logs_user_time ON auth_audit_logs (user_id, occurred_at DESC);
CREATE INDEX ix_auth_audit_logs_username_time ON auth_audit_logs (username, occurred_at DESC);
CREATE INDEX ix_auth_audit_logs_time ON auth_audit_logs (occurred_at DESC);

CREATE FUNCTION reject_auth_audit_log_change() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'auth_audit_logs chỉ cho phép thêm mới, không được % (QTN-02)', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$;

CREATE TRIGGER trg_auth_audit_logs_no_update_delete
    BEFORE UPDATE OR DELETE ON auth_audit_logs
    FOR EACH ROW EXECUTE FUNCTION reject_auth_audit_log_change();

CREATE TRIGGER trg_auth_audit_logs_no_truncate
    BEFORE TRUNCATE ON auth_audit_logs
    FOR EACH STATEMENT EXECUTE FUNCTION reject_auth_audit_log_change();
