-- =====================================================================
-- Câu lạc bộ (bản tối thiểu cho đăng nhập), phạm vi câu lạc bộ của tài khoản, máy quầy lễ tân.
-- NCL-02-CN-001 bổ sung địa chỉ, giờ hoạt động, khu tập bằng migration mới.
-- =====================================================================

CREATE TABLE branches (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL,
    name       VARCHAR(150) NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_branches_code UNIQUE (code),
    CONSTRAINT ck_branches_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX uq_branches_name ON branches (lower(name));

-- Câu lạc bộ được giao cho tài khoản (khi users.all_branches = FALSE). NCL-01-CN-004 hoàn thiện phân quyền.
CREATE TABLE user_branch_scopes (
    user_id   BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    branch_id BIGINT NOT NULL REFERENCES branches (id),
    PRIMARY KEY (user_id, branch_id)
);

CREATE INDEX ix_user_branch_scopes_branch ON user_branch_scopes (branch_id);

-- Máy quầy lễ tân đã đăng ký với một câu lạc bộ. Chỉ lưu SHA-256 của mã máy quầy.
CREATE TABLE counter_devices (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id              BIGINT       NOT NULL REFERENCES branches (id),
    name                   VARCHAR(100) NOT NULL,
    token_hash             VARCHAR(64)  NOT NULL,
    status                 VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    registered_by_user_id  BIGINT       NOT NULL REFERENCES users (id),
    registered_at          TIMESTAMPTZ  NOT NULL,
    last_seen_at           TIMESTAMPTZ,
    revoked_at             TIMESTAMPTZ,
    CONSTRAINT uq_counter_devices_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_counter_devices_token_hash CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_counter_devices_status CHECK (status IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT ck_counter_devices_revoked CHECK ((status = 'REVOKED') = (revoked_at IS NOT NULL))
);

CREATE UNIQUE INDEX uq_counter_devices_branch_name_active
    ON counter_devices (branch_id, lower(name)) WHERE status = 'ACTIVE';

ALTER TABLE user_sessions
    ADD CONSTRAINT fk_user_sessions_device FOREIGN KEY (device_id) REFERENCES counter_devices (id),
    ADD CONSTRAINT fk_user_sessions_branch FOREIGN KEY (branch_id) REFERENCES branches (id);

ALTER TABLE auth_audit_logs
    ADD CONSTRAINT fk_auth_audit_logs_device FOREIGN KEY (device_id) REFERENCES counter_devices (id),
    ADD CONSTRAINT fk_auth_audit_logs_branch FOREIGN KEY (branch_id) REFERENCES branches (id);
